// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package au.org.intersect.sydma.webapp.domain;

import java.lang.String;

privileged aspect MasterVocabulary_Roo_JavaBean {
    
    public String MasterVocabulary.getName() {
        return this.name;
    }
    
    public void MasterVocabulary.setName(String name) {
        this.name = name;
    }
    
}
