Dear $firstName$ $surname$,

One of your colleagues has indicated that a subset of your research data is ready for advertising in Research Data Australia (http://services.ands.org.au/home/orca/rda/).

Advertising your data raises your research profile, increases your Google ranking and promotes your research.
 
Research Dataset: $datasetName$
Research Project: $projectName$
Research Group: $groupName$

Advertising Requested By: $requestedBy$

You can approve or reject this request through $advertiseUrl$ in Agriculture and Environment Data Manager.
